events {}

http {
  include       mime.types;
  default_type  application/octet-stream;

  sendfile on;
  keepalive_timeout 65;

  server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    ###############################
    # 1. Assets del FRONTEND
    ###############################
    location /assets/ {
      try_files $uri =404;
    }

    ###############################
    # 2. Assets del BACKEND (FOTOS)
    ###############################
    location /backend-assets/ {
      # Redirigimos a backend/assets
      rewrite ^/backend-assets/(.*)$ /assets/$1 break;
      proxy_pass http://backend:4000;
      proxy_set_header Host $host;
    }

    ###############################
    # 3. API del backend
    ###############################
    location /api {
      proxy_pass http://backend:4000/api;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    ###############################
    # 4. SPA fallback
    ###############################
    location / {
      try_files $uri $uri/ /index.html;
    }
  }
}