services:
  frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
    container_name: frontend
    restart: always
    ports:
      - "3000:80" # 3000 externo → 80 interno (Nginx)
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    container_name: backend
    restart: always
    environment:
      PORT: 4000
      DATABASE_URL: "postgresql://postgres:password@db:5432/postgres"
      JWT_SECRET: "devsecret"
      SALT_ROUNDS: 10
      FRONTEND_ORIGIN: "http://localhost:3000"
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
