services:
  frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
    container_name: frontend
    restart: always
    ports:
      - "3000:80" # 3000 externo → 80 interno (Nginx)
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    container_name: backend
    restart: always
    environment:
      PORT: 4000
      DATABASE_URL: "postgresql://postgres:${POSTGRES_PASSWORD_DOCKER}@db:5432/${POSTGRES_DB_DOCKER}"
      JWT_SECRET: "${JWT_SECRET_DOCKER}"
      FRONTEND_ORIGIN: "${DOMAIN}"
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD_DOCKER}"
      POSTGRES_DB: ${POSTGRES_DB_DOCKER}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
